# commands/export.py (Clean version - no separators)
from telegram import Update, InputFile
from telegram.ext import ContextTypes
from utils import is_rate_limited
from database import cursor, get_employee, today_ist, now_ist
from datetime import date, datetime
import csv
import io

async def export_csv(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    
    # Rate limit check
    if is_rate_limited(user_id):
        await update.message.reply_text("⏰ Too many requests. Please wait a moment.")
        return
    
    employee = get_employee(user_id)
    
    if not employee or not employee[4]:
        await update.message.reply_text("👑 Admin access required.")
        return
    
    employee_id, org_id, name, balance, is_admin, org_name, join_code, dept, email = employee
    
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Header
    writer.writerow(['ATTENDANCE REPORT', org_name])
    writer.writerow(['Report Date', now_ist().strftime('%Y-%m-%d %H:%M:%S')])
    writer.writerow([])
    
    # Employee Summary
    writer.writerow(['EMPLOYEE SUMMARY'])
    writer.writerow(['Employee Name', 'Department', 'Email', 'Leave Balance', 'Total Present', 'Total Leaves Taken', 'Status', 'Join Date'])
    
    cursor.execute('''
        SELECT name, department, email, leave_balance, total_present, total_leaves_taken, 
               CASE WHEN is_active = 1 THEN 'Active' ELSE 'Inactive' END as status,
               join_date
        FROM employees 
        WHERE org_id = ? 
        ORDER BY name
    ''', (org_id,))
    
    for row in cursor.fetchall():
        writer.writerow(row)
    
    writer.writerow([])
    
    # Monthly Attendance
    current_month = today_ist().strftime("%Y-%m")
    month_name = today_ist().strftime("%B %Y")
    
    writer.writerow([f'MONTHLY ATTENDANCE - {month_name}'])
    writer.writerow(['Employee Name', 'Department', 'Present Days', 'Leave Days', 'Attendance Rate (%)'])
    
    cursor.execute("SELECT id, name, department FROM employees WHERE org_id = ?", (org_id,))
    employees = cursor.fetchall()
    
    for emp_id, emp_name, emp_dept in employees:
        cursor.execute('''
            SELECT 
                SUM(CASE WHEN status = 'present' THEN 1 ELSE 0 END) as present_count,
                SUM(CASE WHEN status = 'leave' THEN 1 ELSE 0 END) as leave_count
            FROM attendance
            WHERE employee_id = ? AND strftime('%Y-%m', date) = ?
        ''', (emp_id, current_month))
        result = cursor.fetchone()
        
        present = result[0] if result[0] else 0
        leaves = result[1] if result[1] else 0
        total_days = present + leaves
        attendance_rate = round((present / total_days * 100) if total_days > 0 else 0, 1)
        
        writer.writerow([emp_name, emp_dept or '-', present, leaves, f"{attendance_rate}%"])
    
    writer.writerow([])
    
    # Recent Attendance Records
    writer.writerow(['RECENT ATTENDANCE RECORDS (Last 30 days)'])
    writer.writerow(['Date', 'Employee Name', 'Department', 'Status', 'Marked At'])
    
    cursor.execute('''
        SELECT a.date, e.name, e.department, a.status, a.marked_at
        FROM attendance a
        JOIN employees e ON a.employee_id = e.id
        WHERE e.org_id = ?
        ORDER BY a.date DESC, a.marked_at DESC
        LIMIT 100
    ''', (org_id,))
    
    for row in cursor.fetchall():
        date_obj = datetime.strptime(row[0], "%Y-%m-%d")
        formatted_date = date_obj.strftime("%b %d, %Y")
        writer.writerow([formatted_date, row[1], row[2] or '-', row[3].upper(), row[4]])
    
    writer.writerow([])
    
    # Leave Balance Summary
    writer.writerow(['LEAVE BALANCE SUMMARY'])
    
    cursor.execute('''
        SELECT 
            SUM(CASE WHEN leave_balance = 4 THEN 1 ELSE 0 END) as full_leaves,
            SUM(CASE WHEN leave_balance BETWEEN 1 AND 3 THEN 1 ELSE 0 END) as partial_leaves,
            SUM(CASE WHEN leave_balance = 0 THEN 1 ELSE 0 END) as no_leaves
        FROM employees WHERE org_id = ?
    ''', (org_id,))
    stats = cursor.fetchone()
    
    writer.writerow(['Total Employees', len(employees)])
    writer.writerow(['Employees with full leaves (4/4)', stats[0] or 0])
    writer.writerow(['Employees with partial leaves (1-3)', stats[1] or 0])
    writer.writerow(['Employees with no leaves left', stats[2] or 0])
    
    writer.writerow([])
    writer.writerow(['Report generated by Attendance Bot'])
    
    # Send the file
    output.seek(0)
    filename = f"{org_name}_Attendance_Report_{today_ist().strftime('%Y-%m-%d')}.csv"
    file = InputFile(output.getvalue().encode('utf-8'), filename=filename)
    
    await update.message.reply_document(
        document=file, 
        caption=f"📊 {org_name} - Attendance Report\n"
                f"📅 {now_ist().strftime('%B %d, %Y')}\n"
                f"👥 {len(employees)} employees\n\n"
                f"Open in Google Sheets or Excel"
    )